#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

#PROJECT_NAME := sample_project
PROJECT_NAME := STUDY_ESPIDF

include $(IDF_PATH)/make/project.mk
